global:
  postgresql:
    auth:
      existingSecret: "postgres-db-secret"
      secretKeys:
        adminPasswordKey: "postgres-password"
        userPasswordKey: "keycloak-password"
      database: "keycloak_db"
      username: "keycloak_admin"
architecture: standalone
primary:
  persistence:
    existingClaim: postgres-pvc
volumePermissions:
  enabled: true
