# --- 공통 설정 부분 ---
auth:
  adminUser: "admin"
  existingSecret: "keycloak-admin-secret"
  passwordSecretKey: "admin-password"
postgresql:
  enabled: false
externalDatabase:
  host: "platform-db-postgres-postgresql.platform-db.svc.cluster.local"
  port: 5432
  user: "keycloak_admin"
  database: "keycloak_db"
  existingSecret: "keycloak-db-secret"
  existingSecretPasswordKey: "keycloak-password"
# 리버스 프록시 인식 활성화
proxy: edge
# Ingress 노출 설정
ingress:
  enabled: true
  ingressClassName: traefik
  hostname: auth.210.113.225.245.nip.io
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
