# ⚠️ 재암호화 필요: strict scope로 암호화되어 있으므로
# namespace 변경 후 아래 명령어로 재암호화가 필요합니다:
# kubeseal --format=yaml --re-encrypt < keycloak-sealed-secret.yaml > keycloak-sealed-secret-new.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-secret
  namespace: platform-iam
spec:
  encryptedData:
    admin-password: AgAPCjMcM6hFudV//jqd1PLx1ZnO/6uumEisBt2u6J72TBBZNNwg0IUipZlqdRduKAxJe53iGPH+RiWtN1TFzAjeNhVN+ZSk5wLn8K1OnWXWLAaPA4a32gaThxrS0Ncn7Uq32zpxyOiETSiqQ/CfHf4rqAqoIxgCoUhbHUpn/fo082za0ZLDYtwURmECPYtZ1g7Q/l3QUHcXfq0ZvknC7dsRx6BPJSM6y6KcPjB1nR7Z3wNGmRM1aUvoZHA+jf8XB0/dcJg19mvC17LSiiRvn4T+l7oPv9hLlBgpauRsZ0ZNTA/1dd9iX6LkwN1PUi3JKsG8LRqYpy8CVUPUet2nairGDvDOphToT4GCrhzt6onsgkvACWBQgKC1r5CQYjtqK1Gfq0w+xpX6H54284+rOtaNx6GfmwXSebdNOK5Je/y0F/m7OCaVd0PJl1VOjxgwVN7B4zBFqyI0Pili0IaE4WHRA+zkEpVaHqKxFMkrGEb8gs95WoYMXUYtoolQ8+loduW+QsxuiPI4W0cFDZyMM2c/N2tn8R4qRfRSMJQPvBhCGt7Kur+zCXrTH4lWc4W7w3EKpXgLRJldf/chDfB7h1sPbyWY+rLQVTJEaE4T0x6j5UNBN+JaEmuPhfNl5NVdE4wgwu+vKSl4YqfAF8ddg05xGRLQDESpKHJDH1bIfOr47kHXmr5g6fYCScinl+pAdQeLd1OkvyoonvSRXTsn5n7Y9C2kN2KGgcdGY4LnsM5Nnw==
  template:
    metadata:
      name: keycloak-admin-secret
      namespace: platform-iam
