apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-secret
  namespace: platform-iam
spec:
  encryptedData:
    keycloak-password: AgCiPpjJaYvxnzyJHgCbTdULs+nVGY+MfRG+JX3RrRoFknanHQzX+mN6Mx7e3g0aDOcmQVoaStG/pA5JMqPATmJZTnytVU6tiuZGtxMGJcTd8u8AH1rASXL35oZUv6Udos5A/Fvy/e85H4o47OwsuwLgBjPX13lOrmcELDRiyNzK+HRuDIDAWAhIS9q0bFgnTj6WCJ5OwyONR2klYbUi02UFkHQ4NaraZgivAuuMLAPyIzmP+aKalmaVyPFavqH6gpCfheLA/z52TOjvM+n4SoeD0az7O+2GsKHlgdmxB5e3Cb2mHELt1Hdz0pUHzSqab31nUGzxCzfAnFPcw/GuYC1MyPS2Xt4KJ4bo6UbbXpnarkmcvRhhBOoTM0VLa+wjDLCPHNlr/t7X/8IR+sRCYYFTVpR02mSQMhi89IlDLomQkqAjdlFCeHuq4WUZGxNRs5w8O5avTUyXnfBZC1VZXDZY+BJ6GmATB9BDTUhm+9XOkJbPGLVvcmhBpPjceA8Qm+s0o1R9lxH+yPg1b5i6XoLLXWuYcOq6mE0bojl8d8wkZMGtVeilPRNPGVquP6emHIElcJmfX2DBH5LVtxnApsQQWFwe/GB/eh0a5JC9G1HGjYxZYdZpcRA+hKL0WgByweXoc2n7FmWcXvm7UNsUGXeLlWGEcgbMcBqlbyWry4FbNmozZ+lXNt1ZiBMhV1cI9gJVmigtL5xgrgpGMYfVyIMfjgAjzvxsM6s+l5eYk/gUkQ==
  template:
    metadata:
      name: keycloak-db-secret
      namespace: platform-iam
