apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-secret
  namespace: platform-iam
spec:
  encryptedData:
    keycloak-password: AgAQ8FgeD/uFIX0D4tHrTDbwYZZyxwhi2ReokEjTrHD+3eFigrQ0fO3kDpKViUfl2K/Bu3Yo/1wJ8qA+8pP6hoOzXsCDO5LQBtsD52swPpRgsVxXr8yUyec0gZvqr+dR5b2eGalmVoKI7MLBKAr1QqfFd1NSmBIz1fENbgnjIczgbZ0lAA6XIMilg+GCOsOYGrhg+jimHApL3wMs97WhpBFrkmTQhX9XcLojuMS4X0tT3og5wgeHBikU8VwzMUbRqqxtQzT8aKRvhxG7FDmIr3zYQHTviCQc7wESDf9i8cikDs3fdlrke1GZPWYd5xRUTxiilRaaIBukKGv6BrJXf0Uts7Eev3iuUhw2n8J6dy5hPBhGnZ/kZAZGBpDpDzN/Ua0DkFD7woBlZNqzCaaK64tlXxhNQWaH/uFnfvnUELJ6N2KPY5Tcpdy6LHOWmtC2JSbp2xNrbp3kPC3r1xDtFt4xCCeWq0Dc2zyJuaGlennyIKqU2veKZTFMIFCGuia9fN5e6DLBWULbQDOueWDeqzfsvyjV3SSZ1olpPHXfXf3xuTqa2P4ATff2Hc1BATLA76G9VCCF8d8vDBp0Pks6ZyDrPHYuMoe+5AR3kdtQL3UrVFj20VqppVSs4oaDLlk2bcb9PbEVoNwx317mAgw7tMkHL5HHFZ69gukI71CTJzEVci9PpeJyg+HXajAysIeVvQ4g07NgGB+Q0ZXF9iU=
  template:
    metadata:
      name: keycloak-db-secret
      namespace: platform-iam
