apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-secret
  namespace: platform-iam
spec:
  encryptedData:
    admin-password: AgAFUsZuiE5VU7sIrHs7UMNu7tcxubH7eZdx0N8VW73ANUmTiW1NTBWx7hAszM3fplzVqb+jlsr2tz/rdKcG4Zede0K7mRnmnrIMK9dSEH5a49QVdM5t1QHIUGWhIwAi6xyArmxhW+wbh363TWfGprV3SlEjqEmnoeH+n5jKjIEHsSXE9UPiO75D/6cwHIf8CLhgTOadVVAvpgXX1dcGJtiB7b6M4zEul5icOngaVynqNozsSxvlN51KOhSzxbm4on70qla/C17xOI3xV9zo3q2Z6/bnl+w63/9pufSTbBJtHbIe3xDtdeC2Xb1XXiUMCIEGaIBpyVRwTIMqy+O9QYR2jvf42myACBn1jksCqLXvDOOjbWEruOydWwLyE5FYuKr9cF5DAjyNoBCH+Gl6LtQoXt0XAkrRKaRWyDR/UzDft/W2ZDhx79VPfaenOjSoqgL6QYThDjv+yEynoevMvleojvqrRgZdU3xGzyqGss4f18ffOwA75OaFpzqJp86gX4aWLCIgVKXB3SF5bVtj4l1kIzbvePUl0acPV693m1ew4jhMnnyAp75ZZ9h/UCN/2laNOlIXm0GDMuqbi2U2QeW7P3kr/fgJ/AXNILRTPsXJ41SozrztdE0+2R1sLzMzJJdVxd7rC1PWM18BFCSwezB36+RtnQRGhWK9UMjG6gkhA0QvNynS/V1jvbzpxxN7vLQLag4COS37TCVLKYE=
  template:
    metadata:
      name: keycloak-admin-secret
      namespace: platform-iam
