apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-secret
  namespace: platform-iam
spec:
  encryptedData:
    admin-password: AgCJ/k1ximY0tJGqP6x6tvFi69w01YloctWfP/a8OQ8wt5b3wqVK7bt1JBGwd0tkCqRM2kxkB7WvEAlwDr+As5pufWMNgHBXmhpCBT9/jBiqe1Ssv75ZS02I8sgSgKzjSwLREsDqRzTV5NHkrz5vQp3VoIzzNCTXpAVNuZ35M1B4Cpr277rV+eUGF6Zus2utKx5Krm9pd9N/Vis7a0je67++MflgEe0IrVcuhp15K+YhmfxHE7fVs/pawK4Adh3JNmb+9HIKAbAR/W1EU1NpmZij4jGeWzJpsTeygqC4WGnpFYeGaAoVh9ji3PrJE+sBjikS1ZgnzeFUuAxGFT/SMw01F7nraKqys6OCnQatqKKg5vZPhpAPl1tWCyMjFL3WgvDZe+M08WGrD/MBUmhHn4oz7nhZmAzCpx+rQMrnYTy3lXFYpAQ9gOLja1pwQ23MmeqaxQRND3n3Lt4E18XFuq2mlqW5l5CASMG6Mzg9Z1MD00a0+BUmR1u1l5MDAd49o3aDcpT+OrhGTHuXD8Ca1KNWwdPYzkbmN4OfP9/7Vl3unnQ9DUedaBa+Hy95E+JVJIMaH87AaAjeIypDUmzcp11BF74aHs2n2pGtV0LYwEwEHlFfOOVBFNHFIKKF8Tr8tEGTOOAOgIfKMI7CN7QwCHHFi+gqepJC5DWZ0qJ5ZHjY1R93254eu3UwxkvCWtE7VKdVHr7Dfzic1QXkZSYBBrKS64EF5i9TJuzs3V5A4Ql+ug==
  template:
    metadata:
      name: keycloak-admin-secret
      namespace: platform-iam
