---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-db-secret
  namespace: default
spec:
  encryptedData:
    keycloak-password: AgC0BRoeKBqhCyQlwZ1+d7OMx5PQ8K2eUuOg26HWGWpW/066ZWmXuIdQxbqzs2F1SVzmlec4WDMXpghqEmfigY/vxVy/I1C+pKchuhdSOnHxpplLw0i6I5AwDgiS8nhkhN6fxIftu05Ouvj7RSEDlIXTbT7vhxAyO55Ey4wPDExm/i0nJm5c9QeHd3/pTNSeU2EUqiKgjRqpKePAedA3Mmc+lvKkzoNiKEVEDe7zc/SQRIypAffOlc5jHkRPlyoFtRWKdxug0RN2rfRedhIj2+BrKDAYnYl46XZnC+kbsvk05ae5dw4kw+2wVAk+hYcvvuiM55Ntm1McR0miNl/6XHj1tzA5x/8u+Mt/I/ssILa42e+qvyIZXwPLc42SaBABobWC17q+C12CPvb3p3cvwkTgbaFxmHlIvEJQ3OzKquKYtOpT6NfwIulomXJ6/qPYXiv3jUDQ2SnPatGZDHSx4Om2kqCu8KQP0HKl5EzfrWhCeFf/m+oUn3ssLrm1uhghQjelj5oA1npIsh9H8Z7C7KCe6ML6JFBvhO9WLvta5+QbY4nd/zDicJKlSyTAWTzDyQX9ijGa+H/jiIBoI1tu5N/O/3Y4aRaAZP1dFyYp31RDAUsV5pvtAy5tkxu09tqzxwSF2yDHa6xx4iyFoUyALa0UkH/6VqhGYqBn40cxnX20GaobpNqiDhGw7kQsWbWRvC8nsVgWy90GK27B7RA=
    postgres-password: AgAdPgMP57kI5cPPxIHlG1UtLZE0KhZyuBoXVIlExf1sWcuPGz6vop3lvlTcluxR5+z9jirJSik4VaJ1mmhfANA0Cv5ewSnjvS+X0c+XImMReoZbycm7Cu1/hQ4Iy/q6Qfe+ItM8sK5DngvKCNFc50G5x45BMBMHcqp4UVYOw8Emlgklqg/y/4TvKD1p6biUdp25P2ludRl1MZoDso49QdK1QJvlT7Ox3fStW7SRBHrlRt+FqnrbSy89/WwlHJuYX0IIJ8kA5VBiMLw3MJfa0PBbF2EHEkv5CnGVEgMnfmYXLPIdbV/AW/TJ9CLrUqUqa2bmMTMlJ/rq+tWiMNiOO6kqmTp8mVdXD5J7UMlUhMdTGUwOQB3e3c3JRmqfCY5bscKDyuMm7tEOC1s62yY5F1xTRMvqWBcnNka5bU62SZmhj4LfBHCzhjnz//JpNMhMmYR8Y/9YEcAB+91GltiZQy7RiuMZmy5Y0eFGlvIqunnFkLqIxELmZoIE6CKIDk51tDT25PZE0svDYj0VXHaqOmKEEG2o8IrPfqSnfNeiCqHC/Q3XRLHlp09RrhMpJD4Hc/pCXOtUacVbZmSqXehQZT8bkJ6Mmbw4W0HLSePG4WBADoFDZoiRvjXsxbSoNbQt50fcm6amiVG7/nXEnr6pZBewKqdCfqFhbtgTZRMGkl6P0WLz8kifkviQu4HADwaSeX1urimRkbOnECypv6k=
  template:
    metadata:
      name: postgres-db-secret
      namespace: default
