apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: platform-db
spec:
  encryptedData:
    redis-password: AgASYn41zF/X4kyfGN7Oqzc5p+jZTL9e1aBGbsjAcpK5UXjNw5CZxVscb51gN7d6uBP14IXLIYiKzUzOszLoQfuv4nghHGNLPiAwl0wOrIqFr2F3woRDb+osUuMFqiiKJbkUV/klzVqCjNcSPJ9rskyrSW81Xac7Ay+4o0puZLw8seQ7vKWV++DomQ97Vte7IQPQZTRNV1+9BAL224JASpebuVeQsyrkvmFm5ZALj5zPbiIwca6+AK0UzIl+UZ11YrPa1OIrbgSYTvXOJjzKq7BXpTsVBqepbZH3rZQl682IaS86Qiyguq33lMUPXaUnm0F8JcYGdukqkCDFFC8wVMKwUZdxlj9pXD6Ct+QtFHY9prvHZH3gCZEQvAWe98D+iLdd7RTAjGTYCZEeavCuLJgy2H7jK0z21YPA8JqBvWDrvlg90vXHX4XftvcG/dJH/IKWWII8E/b71YRQMhWoRxUlxqWWLR+cmtQK4AJ7m+ZcZ2IFmtDpKc7ouvp//qIeCfvNpDR1cOWLLovw+bg/3TB9n75tCd1hVAI2v/eRX/Z4Qo8d7dBdbM4Vmm0zgbsF4uqk3MoyKtO4qbCFPTTIc7ynO1bjBP76iSLOTf7nmgNjVPiCsDWzjJSnluZ/bfzfjBiaIdKIUcgWJ4hPpzGzw9CNs+Y/5NoQX8GX/EfiJKU7R/paNdzrkHepf0BAFbIIM0xy1Cid3dHbLojvpd4=
  template:
    metadata:
      name: redis-secret
      namespace: platform-db
