apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: default
spec:
  encryptedData:
    redis-password: test
  template:
    metadata:
      name: redis-secret
      namespace: default
    type: Opaque
