# ⚠️ 재암호화 필요: strict scope로 암호화되어 있으므로
# namespace 변경 후 아래 명령어로 재암호화가 필요합니다:
# kubeseal --format=yaml --re-encrypt < redis-sealed-secret.yaml > redis-sealed-secret-new.yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: platform-db
spec:
  encryptedData:
    redis-password: AgBcNdUVbTVFyrbbNH41SBdZ8JXQmF+DnH1Vg8ygJB9rUFPB8oFbAqdaQZ+kyPTskyEPeWjU/aNwRppE8vMClvHQb/WGeOMO1dEWJcTHZwzFdo64kCVhB3zSkyBMc6grybAkS/dj2Vz77vFzRF9lY3RFhs32WynzQSiZFJ4H+yfMoR5KkwDzIFLSKlTN2v5ihGvZTbYfWyXXfOtjmq4l/8mRMdjHHBV7AWajH7/ObXBtW0mtdlDP3NQBdc1cvs4OsmolsPN+/8gOjtO+L6uYc1adHyaTYbjwRWXvKo2EzTx/TOPVsBFbQYtI5yu/anL3n3s4VrW8QgOZxK2zGF28LDcPV24V4FXT9Sj+InIVeNf5Vwj9rhUTaLvwv0GlKKB2/jtBe3hi/zB1M/BlvKEf5UR0374139eagjVlvd1W3enm0KSfE3gRm0hsGxbDHGnOLTIA0cQSOiYTI6Kyv+XA9mSoh8uReMn6N/fIqoSEzb+kkpuH2QKOB+cvbvPtDvh3TXbNw3KkyusILd0cCPXfstqh1lvK/HrXG/FE3vcu7/S8OZ++9Ee60DOccjjeNDQx4SwtqKny2Z3U3Y4JQUMlLWQZNZt6MQ/MHTT51CvN7co9Zn0nUsAfFdYiEhqrhFbQeon7zCdWnQZGTKNUMqSxcg9u9DKLbS79jAd8/MD5nxrpWVjxYXjKI0fVDvYxDDD37soZ+rNao+NMqsRK70c=
  template:
    metadata:
      name: redis-secret
      namespace: platform-db
