apiVersion: v1
kind: Namespace
metadata:
  name: product-pulse
  labels:
    app.kubernetes.io/part-of: product-pulse
    app.kubernetes.io/managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: product-routine
  labels:
    app.kubernetes.io/part-of: product-routine
    app.kubernetes.io/managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: product-forecast
  labels:
    app.kubernetes.io/part-of: product-forecast
    app.kubernetes.io/managed-by: argocd
