apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-monitoring-prometheus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: platform-infra
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: "83.6.0"
      helm:
        valueFiles:
          - $values/helm-values/monitoring/kube-prometheus-stack-values.yaml
    - repoURL: https://github.com/yhsk9200/gitops-infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
