apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-system-traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: platform-infra
  source:
    repoURL: "https://github.com/yhsk9200/gitops-infra.git"
    targetRevision: main
    path: manifests/traefik
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
