apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-system-sealed-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: platform-infra
  sources:
    - repoURL: "https://bitnami-labs.github.io/sealed-secrets"
      chart: sealed-secrets
      targetRevision: 2.18.4
      helm:
        valueFiles:
          - $values/helm-values/system/sealed-secrets-values.yaml
    - repoURL: "https://gitlab.am.micube.dev/daegu-tp/mfg-data-platform/gitops/platform-infra.git"
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
