apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-db-redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: platform-infra
  sources:
    - repoURL: "https://charts.bitnami.com/bitnami"
      chart: redis
      targetRevision: 25.3.11
      helm:
        valueFiles:
          - $values/helm-values/database/redis-values.yaml
    - repoURL: "https://github.com/yhsk9200/gitops-infra.git"
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: platform-db
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
