apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-monitoring-loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: platform-infra
  sources:
    - repoURL: https://grafana-community.github.io/helm-charts
      chart: loki
      targetRevision: 6.46.0
      helm:
        valueFiles:
          - $values/helm-values/monitoring/loki-values.yaml
    - repoURL: https://gitlab.am.micube.dev/daegu-tp/mfg-data-platform/gitops/platform-infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
