apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-infra-storage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: platform-infra
  source:
    repoURL: "https://gitlab.am.micube.dev/daegu-tp/mfg-data-platform/gitops/platform-infra.git"
    targetRevision: main
    path: manifests/storage
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
