apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-routine-web
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: product-routine
  source:
    repoURL: https://github.com/yhsk9200/family-routine-reward-app.git
    targetRevision: main
    path: deploy/manifests/web
  destination:
    server: https://kubernetes.default.svc
    namespace: product-routine
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
